import type { Metadata } from "next";
import "./globals.css";


import { Manrope } from "next/font/google";

const manrope = Manrope({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-manrope",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          type="text/css"

          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css"
        />

      </head>
      <body
        className={manrope.className}
      >
        {children}
      </body>
    </html>
  );
}
